<a href="https://colab.research.google.com/github/BDhivya-md3/day1/blob/main/day1_ds.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Implementing Numpy using python programming**

In [1]:
import numpy as np
a=[1,2,3,4]
arr1 = np.array(a)
print(arr1)
b=[[1,2,3,4],[4,5,6,7]]
arr2 = np.array(b)
print(arr2)


[1 2 3 4]
[[1 2 3 4]
 [4 5 6 7]]


In [3]:
import numpy as np
import sys
s= np.range(0,10000)
print("size of each element of numpy array in  bytes")



AttributeError: ignored

In [5]:
import numpy as np
import time
a = range(10000)
b = range(10000)
start = time.time()#mark the time
#list comprehension(multiply each element of a and b)
ab = [(a * b)for a,b in zip(a,b)]
end = time.time()# mark the end time
print("total time taken:",end-start)


total time taken: 0.002105712890625


In [6]:
import numpy as np
arr3 = np.array([[1,2,3],[4,5,6]],ndmin=2)#2d np array
print(arr3)

[[1 2 3]
 [4 5 6]]


In [9]:
import numpy as np
arr4=np.array([[1,2,3],[4,5,6]])
print(arr4.dtype)
print(arr4.ndim)
print(arr4.shape)
print(arr4.size)


int64
2
(2, 3)
6


In [10]:
zero1 = np.zeros((2,2))
print(zero1)


[[0. 0.]
 [0. 0.]]


In [12]:
import numpy as np
c = np.arange(3,10,2)
print(type(c))


<class 'numpy.ndarray'>


In [13]:
a = [1,2,3,4,5]
b=np.array(a)
print(b)
#slicing- creating substrings from the main string,if we want to divide the elements in list
#indexing - getting the value from a specific index position ,or range to upper range 
#range(lower,upper+1)-0 to 10(0,11)
b[1]
b[4]

[1 2 3 4 5]


5

In [14]:
b[0:3]

array([1, 2, 3])

In [16]:
b[0]=10
print(b)


[10  2  3  4  5]


In [17]:
#2nd index to remaining
print(b[2: ])

[3 4 5]


In [18]:
print(b[ :3])

[10  2  3]


In [19]:
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])
c
print(c[1])
print(c[1][3])

[ 6  7  8  9 10]
9


# **pandas library implementation**

In [ ]:
dataset.shape
dataset.info()
#dsecription of dataset
dataset.describe()
dataset1=pd.read_html('https://en.wikipedia.org/wiki/Data_science')
dataset[['Age','estimation','purchased']]